project:
  type: website
  output-dir: docs
  resources:
    - files/*.pdf

website:
  title: "Olive Edeko"
  favicon: Images/favicon.png
  site-url: "https://oliveedeko.github.io/baa1104-portfolio/"

  navbar:
    left:
      - text: Home
        href: index.qmd
        icon: house
      - text: About
        href: about.qmd
        icon: person
      - text: Projects
        href: projects/index.qmd
        icon: bar-chart
      - text: Reflections
        href: reflections.qmd
        icon: journal-text
      - text: Media
        href: media.qmd
        icon: film
      - text: Contact
        href: contact.qmd
        icon: envelope

    right:
      - text: CV
        href: Olive_Edeko_CV_2026.pdf
        icon: file-earmark-text
      - icon: github
        href: https://github.com/oliveedeko
      - icon: linkedin
        href: https://www.linkedin.com/in/oliveedeko

  page-footer:
    left: "© Olive Edeko"
    right: "Built with Quarto"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    page-layout: full